# Generated by Django 5.2.8 on 2025-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
